// Board version (DTEK-V): switches choose image / kernel / blur, a button runs it.
// Uses only the lab-library functions print() and print_dec(); no printf, memcpy or abs.
// commands: jtagconfig / make / dtekv-run main.bin / (optional killall jtagd)

#include <stdint.h>         //fixed-size types: uint8_t (0...255), int8_t (-128..127), uint32_t

//64x64 pixels, generated by img_to_c.py
#include "image_mug.h"      // const uint8_t image_mug[4096]
#include "image_shapes.h"   // const uint8_t image_shapes[4096]
#include "image_noisy.h"    // const uint8_t image_noisy[4096]

// lab-library output functions (same as in lab 3)
extern void print(const char *);        // prints a string to the terminal; defined in the lab library
extern void print_dec(unsigned int);    // prints an unsigned number in decimal;

#define IMG_WIDTH  64            // image width in pixels
#define IMG_HEIGHT 64            // image height in pixels
#define IMG_SIZE   (IMG_WIDTH * IMG_HEIGHT)  // total number of pixels = 4096 (one byte each)
#define EDGE_THRESHOLD 50        // an output pixel brighter than this counts as an "edge"
#define MARGIN 3                // border (in pixels) ignored when counting edges, because
                                // the kernels leave the border at 0 (LoG + blur need up to 3)

// Empty interrupt handler called by the boot code, so it must exist
// We use polling only, so interrupts are never enabled and it is never called.
void handle_interrupt(unsigned cause) {

}
// ---------------- board I/O (addresses from lab 3) ---------------- // volatile = the compiler must really do the access
void set_leds(int led_mask) {    // writes a bit pattern to the LEDs
    volatile unsigned int * const led_ptr = (unsigned int *) 0x04000000; // fixed (=cost) address of the LED register;
    *led_ptr = led_mask; // bit n of the mask lights LED n
}
int get_sw(void) {    // reads the state of the switches
    volatile unsigned int * const sw_ptr = (unsigned int *) 0x04000010; // fixed (=cost) address of the switch register
    return (*sw_ptr) & 0x3FF;      // read it, keep only the lowest 10 bits (SW0..SW9)
}
int get_btn(void) {    // reads the push button
    volatile unsigned int * const btn_ptr = (unsigned int *) 0x040000d0;    // fixed address of the button register
    return (*btn_ptr) & 0x1;       // second push button, keep only bit 0: 1 = pressed, 0 = released
}

// ---------------- images ----------------
typedef struct {        // one entry of the image table
    const char    *name;    // text used when printing results (e.g. "mug")
    const uint8_t *data;    // pointer to the 4096 pixel values in memory
} Image;

const Image images[] = {        // table indexed by img_id
    {"mug",    image_mug},      // index 0 <- SW1..SW0 = 01
    {"shapes", image_shapes},   // index 1 <- SW1..SW0 = 10
    {"noisy",  image_noisy},    // index 2 <- SW1..SW0 = 11
};

// ---------------- kernels ----------------
typedef struct {             // one entry of the kernel table
    const char   *name;      // text used when printing results
    const int8_t *k;         // pointer to the kernel coefficients (row by row)
    int size;                // kernel is size x size (3 or 5)
    int div;                 // the weighted sum is divided by this value
                            // (9 for blur = average of 9 pixels, 1 = no scaling)
} Kernel; 

const int8_t k_sobel_x[9]   = { -1,0,1,  -2,0,2,  -1,0,1 }; //detects vertical edges (horizontal intensity change)
const int8_t k_sobel_y[9]   = { -1,-2,-1,  0,0,0,  1,2,1 };// detects horizontal edges (vertical intensity change)
const int8_t k_laplacian[9] = { 0,1,0,  1,-4,1,  0,1,0 };//second derivative: responds to edges in all directions

const int8_t k_blur[9]      = { 1,1,1,  1,1,1,  1,1,1 }; //box blur: sum of 9 pixels, divided by 9 (average)
const int8_t k_log[25]      = {  0, 0,-1, 0, 0,    // Laplacian of Gaussian, 5x5: smooths and finds edges
                                 0,-1,-2,-1, 0,    // in one step (centre value 16 balances the negatives)
                                -1,-2,16,-2,-1,
                                 0,-1,-2,-1, 0,
                                 0, 0,-1, 0, 0 };

const Kernel kernels[] = {        // table indexed by kernel_id
    {"Blur",      k_blur,      3, 9},   // 0 (only used as the pre-blur step), 9 is the divisor
    {"Sobel_X",   k_sobel_x,   3, 1},   // 1
    {"Sobel_Y",   k_sobel_y,   3, 1},   // 2
    {"Laplacian", k_laplacian, 3, 1},   // 3
    {"LoG",       k_log,       5, 1},   // 4
};
// Convolution: slides the kernel K over in_buf and writes the result to out_buf.
void apply_kernel(const uint8_t *in_buf, uint8_t *out_buf, const Kernel *K) {
    int r = K->size / 2;                                // kernel radius: 1 for 3x3, 2 for 5x5
    for (int i = 0; i < IMG_SIZE; i++) out_buf[i] = 0;  // clear output, so the frame border stays black

    for (int y = r; y < IMG_HEIGHT - r; y++) {      // rows where the whole kernel fits inside the image
        for (int x = r; x < IMG_WIDTH - r; x++) {    // columns where the whole kernel fits
            int sum = 0;      // weighted sum for this pixel
            for (int ky = -r; ky <= r; ky++) // kernel row offset around the current pixel
                for (int kx = -r; kx <= r; kx++)      // kernel column offset
                    sum += in_buf[(y + ky) * IMG_WIDTH + (x + kx)]     // neighbour pixel (2D -> 1D index: row*width + col)
                         * K->k[(ky + r) * K->size + (kx + r)];    // times the matching kernel coefficient
            sum /= K->div;   // normalise (only blur has div > 1)                         
            if (sum < 0) sum = -sum;        // keep the edge strength, ignore its sign
            if (sum > 255) sum = 255;        // fixed it to the 8-bit range
            out_buf[y * IMG_WIDTH + x] = (uint8_t)sum;    //store the result pixel
        }
    }
}
// Counts the pixels brighter than the threshold, ignoring a border of MARGIN pixels.
int count_edges(const uint8_t *buf, int threshold) {
    int n = 0;        // edge pixel counter
    for (int y = MARGIN; y < IMG_HEIGHT - MARGIN; y++) //skip the border rows
        for (int x = MARGIN; x < IMG_WIDTH - MARGIN; x++) // skip the border columns
            if (buf[y * IMG_WIDTH + x] > threshold) n++;    // pixel above the threshold = edge
    return n;        // number of edge pixels
}

static uint8_t bufA[IMG_SIZE]; // working buffer A (4096 bytes in RAM; static = lives for the whole program)
static uint8_t bufB[IMG_SIZE]; // working buffer B

// returns the buffer that holds the result
const uint8_t *process(const Image *img, int kernel_id, int use_blur) {
    for (int i = 0; i < IMG_SIZE; i++) bufA[i] = img->data[i];   // own memcpy:copy the original (read-only) image into A
    if (use_blur) {        // blur first, then the edge kernel
        apply_kernel(bufA, bufB, &kernels[0]);           // blur: A -> B
        apply_kernel(bufB, bufA, &kernels[kernel_id]);   // edge: B -> A
        return bufA;    // final result is in A
    }
    apply_kernel(bufA, bufB, &kernels[kernel_id]);       // edge: A -> B
    return bufB; // final result is in B
}

// "download": print the result as a text PGM, one image row per line
void print_pgm(const uint8_t *buf) {
    print("P2\n64 64\n255\n"); // PGM header: P2 = plain-text grayscale, width height, max value
    for (int y = 0; y < IMG_HEIGHT; y++) {    // one text line per image row
        for (int x = 0; x < IMG_WIDTH; x++) {    // every pixel of the row
            print_dec(buf[y * IMG_WIDTH + x]);   // pixel value as a decimal number
            print(" ");    // separator between values
        }
        print("\n");    // end of the row
    }
}

int main(void) {
    int last_btn = 0;   // previous button state: one press = one run

    print("Ready. SW1-0: image (01 mug, 10 shapes, 11 noisy).\n");
    print("SW2: Sobel_X, SW3: Sobel_Y, SW4: Laplacian, SW5: LoG. SW6:blur first.\n");
    print("Raise ONE kernel switch, SW6 blur, then press button to run.\n");

    while (1) {    // polling loop: runs forever, no interrupts
        int sw = get_sw();      // read all switches (one bit per switch)
        int img_sel = sw & 0x3; //keep least significant bit: SW1-SW0: 0=nothing, mug=01, shapes=10, noisy=11
        int k_sel = (sw >> 2) & 0xF;           // 4 bits for the 4 kernels in switches SW2-SW5
        int use_blur  = (sw >> 6) & 0x1;   // SW6: blur first (back-to-back), 1=blur, 0=noblur

        int img_id = img_sel - 1; // 01->0 mug, 10->1 shapes, 11->noisy, 00->-1 none

        int kernel_id = 0; // 0= none/invalid until one kernel swich is up
        if      (k_sel == 1) kernel_id = 1; //SW2 only: Sobel_X 0001
        else if (k_sel == 2) kernel_id = 2; //SW3 only: Sobel_Y  0010  
        else if (k_sel == 4) kernel_id = 3;//SW4 only: Laplacian    0100
        else if (k_sel == 8) kernel_id = 4;//SW5 only: LoG 1000

        set_leds(sw & 0x7F);   // mirror the current selection (SW0...SW6) on the LEDs

        int btn = get_btn(); //read the button now
        if (btn && !last_btn) { //rising edge button: pressed now and not pressed before = one new press
            if(img_id < 0){    // SW1-0 = 00: no image chosen
                print("No image selected (SW1-0 = 00)\n"); // comment line, ignored by the PGM reader
                }
            else if(k_sel == 0){ // no kernel switch: show the input image
                print("# "); // comment line, ignored by the PGM reader
                print(images[img_id].name);// image name
                print(", input\n");
                print_pgm (images[img_id].data); // print the original pixels
                }
            else if(kernel_id == 0){ // several kernel switches up at once: invalid
                print("Select only one kernel among SW2, SW3, SW4, SW5\n");
            }
            else{    // valid image and exactly one kernel
                set_leds((sw & 0x7F) | 0x200);   // LED9 on = busy, 0x200= bit 9
                const uint8_t *res = process(&images[img_id], kernel_id, use_blur); // compute the result image
                print("# "); // header line: image, kernel, blur, edge count
                print(images[img_id].name);
                print(", ");
                print(kernels[kernel_id].name);
                print(use_blur ? ", blur, edges=" : ", no blur, edges="); // text chosen by the blur flag, ? is the same of if/else but compact
                print_dec((unsigned int)count_edges(res, EDGE_THRESHOLD)); // number of edge pixels
                print("\n");
                print_pgm(res);    // print the result image as text
                set_leds(sw & 0x7F); //led9 off = done, showing only the switches kernels led
                }
       
        }
        last_btn = btn; // remember the button state for the next loop pass
    }
    return 0; // never reached (infinite loop)
}
